USE [master]
GO

/****** Object:  Database [DBCaronas]    Script Date: 11/12/2016 15:46:38 ******/
IF ((SELECT COUNT(name)
FROM master.dbo.sysdatabases 
WHERE ('[' + name + ']' = 'DBCARONAS' 
OR name = 'DBCARONAS')) = 0)
BEGIN
	CREATE DATABASE [DBCaronas]
	 CONTAINMENT = NONE
	 ON  PRIMARY 
	( NAME = N'DBCaronas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DBCaronas.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
	 FILEGROUP [CARONAS] 
	( NAME = N'DBCaronas_Caronas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DBCaronas_Caronas.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 40%), 
	 FILEGROUP [USUARIOS] 
	( NAME = N'DBCaronas_Usuarios', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DBCaronas_Usuarios.ndf' , SIZE = 153600KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
	 FILEGROUP [VEICULOS] 
	( NAME = N'DBCaronas_Veiculos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DBCaronas_Veiculos.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
	 LOG ON 
	( NAME = N'DBCaronas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DBCaronas_log.ldf' , SIZE = 265344KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END;
GO

ALTER DATABASE [DBCaronas] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBCaronas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBCaronas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBCaronas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBCaronas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBCaronas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBCaronas] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBCaronas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBCaronas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBCaronas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBCaronas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBCaronas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBCaronas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBCaronas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBCaronas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBCaronas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBCaronas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBCaronas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBCaronas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBCaronas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBCaronas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBCaronas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBCaronas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBCaronas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBCaronas] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBCaronas] SET  MULTI_USER 
GO

ALTER DATABASE [DBCaronas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBCaronas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBCaronas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBCaronas] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBCaronas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBCaronas] SET  READ_WRITE 
GO


