-------------------------Destrói todas as procedures------------------------
IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES
			WHERE ROUTINE_NAME ='GERA_CODIGO_USUARIO'))
BEGIN
	DROP PROCEDURE GERA_CODIGO_USUARIO;
END;

IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES
			WHERE ROUTINE_NAME ='GERA_PONTOS_INTERMEDIARIOS'))
BEGIN
	DROP PROCEDURE GERA_PONTOS_INTERMEDIARIOS;
END;

-------------------------Destrói todas as triggers------------------------
IF EXISTS (SELECT * FROM sys.objects WHERE [name] = N'GERA_COD_USUARIO' AND [type] = 'TR')
BEGIN
      DROP TRIGGER GERA_COD_USUARIO;
END;

IF EXISTS (SELECT * FROM sys.objects WHERE [name] = N'TRG_CONVERSOR_FROM_CARONAAUX' AND [type] = 'TR')
BEGIN
      DROP TRIGGER TRG_CONVERSOR_FROM_CARONAAUX;
END;

IF EXISTS (SELECT * FROM sys.objects WHERE [name] = N'TRG_CONVERSOR_PONTOS_INTERMEDIARIOS' AND [type] = 'TR')
BEGIN
      DROP TRIGGER TRG_CONVERSOR_PONTOS_INTERMEDIARIOS;
END;


-------------------------Destrói todas as constraints------------------------
IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='VEICULO'))
BEGIN
	ALTER TABLE VEICULO
	DROP CONSTRAINT FK_VEICULO_IDUSUARIO;
END;

IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='CARONA'))
BEGIN
	ALTER TABLE CARONA
	DROP CONSTRAINT FK_CARONA_IDUSUARIO;
END;

IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='CARONAAUX'))
BEGIN
	ALTER TABLE CARONAAUX
	DROP CONSTRAINT FK_CARONAIDAUX;
END;

IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='CARONAPONTOSINTERMEDIARIOS'))
BEGIN
	ALTER TABLE CARONAPONTOSINTERMEDIARIOS
	DROP CONSTRAINT FK_CARONAIDINTERMED;
END;


-----------------------Destrói todas as tabelas--------------------------------------

IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='CARONAPONTOSINTERMEDIARIOS'))
BEGIN
	DROP TABLE CARONAPONTOSINTERMEDIARIOS;
END;

IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='CARONAAUX'))
BEGIN
	DROP TABLE CARONAAUX;
END;

IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='CARONA'))
BEGIN
	DROP TABLE CARONA;
END;

IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='VEICULO'))
BEGIN
	DROP TABLE VEICULO;
END;

IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='USUARIO'))
BEGIN
	DROP TABLE USUARIO;
END;

IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='DOMINIOS_EMAIL'))
BEGIN
	DROP TABLE DOMINIOS_EMAIL;
END;


--Destrói as SEQUENCES
DROP SEQUENCE SEQ_CODIGO_USUARIO;


