--Tabela de Usuário
IF NOT (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='USUARIO'))
BEGIN
	CREATE TABLE USUARIO(
		ID UNIQUEIDENTIFIER PRIMARY KEY,
		CODIGO NCHAR(8) UNIQUE,
		CPF NCHAR(11) UNIQUE,
		NOME VARCHAR(50),
		DTNASCIMENTO DATE,
		EMAILINSTITUCIONAL VARCHAR(40),
		EMAILSECUNDARIO VARCHAR(40),
		TELEFONE NCHAR(14),
		POSSUIVEICULO BIT,
		ATIVO BIT,
		SENHA VARCHAR(15)
	);
END;


--Tabela de veículo
IF NOT (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='VEICULO'))
BEGIN
	CREATE TABLE VEICULO(
		ID UNIQUEIDENTIFIER ,
		IDUSUARIO UNIQUEIDENTIFIER,
		PLACA NCHAR(7) PRIMARY KEY,
		MARCA VARCHAR(20),
		MODELO VARCHAR(30)
	);
END;


--Tabela de Carona
IF NOT (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='CARONA'))
BEGIN
	CREATE TABLE CARONA(
		ID uniqueidentifier PRIMARY KEY,
		IDUSUARIO uniqueidentifier,
		DESCRICAO varchar(50),	
		PONTOPARTIDA geography,
		PONTOSINTERMEDIARIOS geography,
		PONTODESTINO geography,
		HORARIOPARTIDA time,
		HORARIOCHEGADA time
	); 
END;


--Tabela auxiliar onde serão armazenados os dados para gerar os registros da tabela Carona
IF NOT (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='CARONAAUX'))
BEGIN
	CREATE TABLE CARONAAUX(
		IDCARONA uniqueidentifier,
		ORIGEMLATITUDE NCHAR(10),
		ORIGEMLONGITUDE NCHAR(10),
		DESTINOLATITUDE NCHAR(10),
		DESTINOLONGITUDE NCHAR(10),	
	);
END;


--Tabela auxiliar onde serão armazenados os dados dos pontos intermediários a serem registros da tabela Carona
IF NOT (EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_NAME ='CARONAPONTOSINTERMEDIARIOS'))
BEGIN
	CREATE TABLE CARONAPONTOSINTERMEDIARIOS(
		IDCARONA UNIQUEIDENTIFIER,
		LATITUDE NCHAR(10),
		LONGITUDE NCHAR(10)
	);
END;

------------------------FOREIGN KEYS

--Chave estrangeira da tabela usuário referenciando um registro na tabela VEICULO
ALTER TABLE VEICULO
ADD CONSTRAINT FK_VEICULO_IDUSUARIO
FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID);

--Chave estrangeira que referencia o ID do usuário (tabela USUARIO) ofertador daquela carona
ALTER TABLE CARONA
ADD CONSTRAINT FK_CARONA_IDUSUARIO
FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID);

--Referência da carona (tabela CARONA) para a qual serão gerados os pontos geography
ALTER TABLE CARONAAUX
ADD CONSTRAINT FK_CARONAIDAUX
FOREIGN KEY (IDCARONA) REFERENCES CARONA(ID);
 
--Referência da carona (tabela CARONA) para a qual serão gerados o MULTIPOINT geography
ALTER TABLE CARONAPONTOSINTERMEDIARIOS
ADD CONSTRAINT FK_CARONAIDINTERMED
FOREIGN KEY (IDCARONA) REFERENCES CARONA(ID);

