CREATE TRIGGER TRG_CONVERSOR_FROM_CARONAAUX
ON CARONAAUX
AFTER INSERT
AS
BEGIN
	set nocount on;

	DECLARE
	@ORIGLONGITUDE VARCHAR(10),
	@ORIGLATITUDE VARCHAR(10),
	@DESTLONGITUDE VARCHAR(10),
	@DESTLATITUDE VARCHAR(10),
	@IDCARONA uniqueidentifier

	SELECT @IDCARONA = IDCARONA, 
		   @ORIGLATITUDE = ORIGEMLATITUDE, @ORIGLONGITUDE = ORIGEMLONGITUDE,
		   @DESTLATITUDE = DESTINOLATITUDE, @DESTLONGITUDE = DESTINOLONGITUDE 
		   FROM INSERTED 
	
	UPDATE CARONA
	SET PONTOPARTIDA = geography::STPointFromText('POINT(' + @ORIGLONGITUDE + ' ' + @ORIGLATITUDE + ')', 4618),
		PONTODESTINO = geography::STPointFromText('POINT(' + @DESTLONGITUDE + ' ' + @DESTLATITUDE + ')', 4618)
	WHERE ID = @IDCARONA;
END; 


--DROP TRIGGER TRG_CONVERSOR_FROM_CARONAAUX;
