CREATE PROCEDURE [DBO].GERA_PONTOS_INTERMEDIARIOS @pontos VARCHAR(200), @IDCARONA UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE
	@MULTIPONTO VARCHAR(230),
	@PONTOORIGEM NCHAR(25)

	SELECT @PONTOORIGEM = (C.PONTOPARTIDA.Long + ' ' + C.PONTOPARTIDA.Lat + ', ')  FROM CARONA C WHERE ID = @IDCARONA;

	SET @MULTIPONTO = 'MULTIPOINT(' + @PONTOORIGEM + @pontos +')'

	UPDATE CARONA 
	SET PONTOSINTERMEDIARIOS = 
		geography::STMPointFromText(@MULTIPONTO, 4618) 
	WHERE ID = @IDCARONA
END;


--DROP PROCEDURE GERA_PONTOS_INTERMEDIARIOS;


