CREATE PROCEDURE [DBO].GERA_PONTOS_INTERMEDIARIOS @pontos VARCHAR(200), @IDUSUARIO UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE
	@MULTIPONTO VARCHAR(230)

	SET @MULTIPONTO = 'MULTIPOINT(' + @pontos +')'

	UPDATE CARONA 
	SET PONTOSINTERMEDIARIOS = 
		geography::STMPointFromText(@MULTIPONTO, 4618) 
	WHERE ID = @IDUSUARIO
END;


--DROP TRIGGER TRG_CONVERSOR_PONTOS_INTERMEDIARIOS;
