CREATE TRIGGER ALTERA_USUARIO_POSSUIVEICULO
ON VEICULO
AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE
	@IDUSUR UNIQUEIDENTIFIER

	SELECT @IDUSUR = IDUSUARIO FROM INSERTED;

	EXEC PROC_ALTERA_POSSUIVEICULO @IDUSUARIO = @IDUSUR, @NOVOCODIGO = '1';

END;

--DROP TRIGGER ALTERA_USUARIO_POSSUIVEICULO