CREATE PROCEDURE PROC_ALTERA_POSSUIVEICULO @IDUSUARIO UNIQUEIDENTIFIER, @NOVOCODIGO VARCHAR(1)
AS
BEGIN
	IF (@NOVOCODIGO = 0) 
	BEGIN
		DELETE FROM VEICULO WHERE IDUSUARIO = @IDUSUARIO;
	END;

	UPDATE USUARIO
	SET POSSUIVEICULO = @NOVOCODIGO
	WHERE ID = @IDUSUARIO;
END;