CREATE PROCEDURE [DBO].PROC_GERA_CODIGO_USUARIO @idUsuario UNIQUEIDENTIFIER, @emailInstitucional VARCHAR(40), @CODIGOUSUARIO NCHAR(8) OUTPUT
AS
BEGIN 
	DECLARE
	@DOMINIO VARCHAR(30),
	@CODIGODOMINIO NCHAR(3),
	@CODIGO VARCHAR(8);

	SET @DOMINIO = SUBSTRING(@emailInstitucional, CHARINDEX('@', @emailInstitucional) + 1, LEN(@emailInstitucional));

	SELECT @CODIGODOMINIO = CODIGO FROM DOMINIOS_EMAIL WHERE UPPER(DOMINIOEMAIL) = UPPER(@DOMINIO);

	SET @CODIGO = @CODIGODOMINIO + REPLICATE('0', (5 - LEN(@CODIGOUSUARIO))) + @CODIGOUSUARIO;

	SELECT @CODIGOUSUARIO = @CODIGO;

end;


--     DROP PROCEDURE PROC_GERA_CODIGO_USUARIO
--DROP function DBO.FUNC_GERA_CODIGO_USUARIO

