CREATE PROCEDURE [DBO].GERA_CODIGO_USUARIO @idUsuario UNIQUEIDENTIFIER, @emailInstitucional VARCHAR(40)
AS
BEGIN 
	DECLARE
	@DOMINIO VARCHAR(30),
	@CODIGODOMINIO NCHAR(3),
	@CODIGOUSUARIO NCHAR(5);

	SET @DOMINIO = SUBSTRING(@emailInstitucional, CHARINDEX('@', @emailInstitucional) + 1, LEN(@emailInstitucional));

	SELECT @CODIGODOMINIO = CODIGO FROM DOMINIOS_EMAIL WHERE UPPER(DOMINIOEMAIL) = UPPER(@DOMINIO);

	SELECT @CODIGOUSUARIO = NEXT VALUE FOR SEQ_CODIGO_USUARIO;


	UPDATE USUARIO
	SET CODIGO = @CODIGODOMINIO + REPLICATE('0', (5 - LEN(@CODIGOUSUARIO))) + @CODIGOUSUARIO
	WHERE ID = @idusuario
end;


--DROP PROCEDURE GERA_CODIGO_USUARIO

