CREATE TRIGGER GERA_COD_USUARIO
ON USUARIO
AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE 
	@IDUSUR UNIQUEIDENTIFIER,
	@EMAILINST VARCHAR(40)

	SELECT 
		@IDUSUR = ID,
		@EMAILINST = EMAILINSTITUCIONAL
	FROM INSERTED;

	EXECUTE GERA_CODIGO_USUARIO @idusuario = @IDUSUR, @emailInstitucional = @EMAILINST;
END;

--DROP TRIGGER GERA_COD_USUARIO