CREATE TRIGGER GERA_COD_USUARIO
ON USUARIO
AFTER INSERT
AS
BEGIN 
	SET NOCOUNT ON;
	DECLARE 
	@IDUSUR UNIQUEIDENTIFIER
	SELECT @IDUSUR = ID FROM INSERTED;
	EXECUTE GERA_CODIGO_USUARIO @idusuario = @IDUSUR;
END;